const cities = [
  "Ahmedabad",
  "Amritsar",
  "Bangalore",
  "Bhopal",
  "Chennai",
  "Delhi",
  "Guwahati",
  "Gwalior",
  "Hyderabad",
  "Jodhpur",
  "Kochi",
  "Kolkata",
  "Lucknow",
  "Mumbai",
  "Nagpur",
  "Panaji",
  "Patna",
  "Visakhapatnam",
];

const cityMappings = {
  Ahmedabad: ["ADI", 380001],
  Amritsar: ["ASR", 143001],
  Bangalore: ["SBC", 560001],
  Bhopal: ["BPL", 462001],
  Chennai: ["MAS", 600001],
  Delhi: ["NDLS", 110001],
  Guwahati: ["GHY", 781001],
  Gwalior: ["GWL", 474001],
  Hyderabad: ["HYB", 500001],
  Jodhpur: ["JU", 342001],
  Kochi: ["ERS", 682001],
  Kolkata: ["HWH", 700001],
  Lucknow: ["LKO", 226001],
  Mumbai: ["CSTM", 400001],
  Nagpur: ["NGP", 440001],
  Panaji: ["QLM", 403001],
  Patna: ["PNBE", 800001],
  Visakhapatnam: ["VSKP", 530001],
};

const parcelsData = [
  {
    parcelId: "P001",
    trackId: "",
    source: "Delhi",
    destination: "Nagpur",
    weight: 50,
    noOfBags: 10,
    path: [],
    type: "outgoing",
    currentNode: "Delhi",
  },
  {
    parcelId: "P002",
    trackId: "",
    source: "Delhi",
    destination: "Patna",
    weight: 50,
    noOfBags: 10,
    path: [],
    type: "outgoing",
    currentNode: "Delhi",
  },
  {
    parcelId: "P003",
    trackId: "",
    source: "Nagpur",
    destination: "Mumbai",
    weight: 50,
    noOfBags: 10,
    path: [],
    type: "outgoing",
    currentNode: "Nagpur",
  },
  {
    parcelId: "P003",
    trackId: "",
    source: "Mumbai",
    destination: "Nagpur",
    weight: 50,
    noOfBags: 10,
    path: [],
    type: "outgoing",
    currentNode: "Mumbai",
  },
  {
    parcelId: "P004",
    trackId: "",
    source: "Patna",
    destination: "Nagpur",
    weight: 50,
    noOfBags: 10,
    path: [],
    type: "outgoing",
    currentNode: "Patna",
  },
  {
    parcelId: "P005",
    trackId: "",
    source: "Patna",
    destination: "Mumbai",
    weight: 50,
    noOfBags: 10,
    path: [],
    type: "outgoing",
    currentNode: "Patna",
  },
];
module.exports = { cities, cityMappings };
